# Generated by Django 5.1.1 on 2024-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
