# Generated by Django 5.1.1 on 2024-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorings', '0002_formresponse_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
